powered_by:         runs on
abstract:           Executive summary
download:           PDF
share:              Share
date_publication:   Published on
keywords:           Keywords
cite_as:            Recommended citation
quote_open:         "&bdquo;"
quote_close:        "&ldquo;"
downloadData:       Download primary data
toc:                Content
toc_long:           Table of contents
questions:          Feedback or questions?
write_mail:         Write an email to
read_on:            Read the full brief
cited_source:       Cited source
authors:            Authors
visit_website:      Visit website
