lang:                   en
styles:                 theme/styles/sample-journal.css
brand:                  graphite – Enhanced publications for a digital environment
brand_url:              "https://www.impactdistillery.com/graphite"
background_url:         assets/images/markus-winkler-afW1hht0NSs-unsplash_b.jpg
short_url:              https://graphite.page/fair-targeted-ads/
social_image_url:       https://graphite.page/fair-targeted-ads/assets/images/social.png
title:                  "Increasing fairness in targeted advertising"
subtitle:               "The risk of gender stereotyping by job ad algorithms"
authors:                Nadine Birner, Shlomi Hod, Matthias C. Kettemann, Alexander Pirang, and Friederike Stock
year:                   2021
cite_as:                "Birner, N., Hod, S., Kettemann, M. C., Pirang, A., & Stock, F. (2021). *Increasing fairness in targeted advertising* [The Ethics of Digitalisation Clinics Report, 1]. Alexander von Humboldt Institute for Internet and Society. https://graphite.page/fair-targeted-ads"
date_publication:       20 Mar 2021
# date_submission:
# date_last_updated:
# logo_url:
pdf_url:                https://doi.org/10.5281/zenodo.4292408
# isbn:                   978-989-746-128-6
doi:                    10.5281/zenodo.4292408
contact_email:          nadine.birner@hiig.de
data_usage:
disclaimer:
author_info:             A report by researchers and fellows of the HIIG clinics on Fairness in Targeted Advertising
author_info_sticky:     true
keywords:               job ads, targeted advertising, algorithms, algorithmic discrimination, gender bias, discrimination, platforms
terms_of_use:
imprint:
licence:
abstract:               "Who gets to see what on the internet? And who decides why? These are among the most crucial questions regarding online communication spaces – and they especially apply to job advertising online. Targeted advertising on online platforms offers advertisers the chance to deliver ads to carefully selected audiences. Yet, optimizing job ads for relevance also carries risks – from problematic gender stereotyping to potential algorithmic discrimination. The spring 2021 Clinic Increasing Fairness in Targeted Advertising: The Risk of Gender Stereotyping by Job Ad Algorithms examined the ethical implications of targeted advertising, with a view to developing feasible, fairness-oriented solutions.\n\n
The virtual Clinic brought together twelve fellows from six continents and eight disciplines. During two intense weeks in February 2021, they participated in an interdisciplinary solution-oriented process facilitated by a project team at the Alexander von Humboldt Institute for Internet and Society. The fellows also had the chance to learn from and engage with a number of leading experts on targeted advertising, who joined the Clinic for thought-provoking spark sessions.\n\n
The objective of the Clinic was to produce actionable outputs that contribute to improving fairness in targeted job advertising. To this end, the fellows developed three sets of guidelines – this resulting document – that cover the whole targeted advertising spectrum. While the guidelines provide concrete recommendations for platform companies and online advertisers, they may also be of interest to policymakers."
matomo_tracking:        true
matomo_url:             "https://piwik.wunderjewel.de/"
matomo_siteId:          "4"

:---------------------------------------------------:
tabs:
  - title: "Article"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "Authors"
    ref: "/authors/"
    slug: authors
    md_container: section
  - title: "References"
    ref: "/directories/"
    slug: directories
    md_container: section
  - title: "About"
    ref: "/editors/"
    slug: editors
    md_container: section
